-- Phase 1: schema setup
-- Database/schema: TIKTOK_DASHBOARD.PUBLIC

-- Raw landing table: one column per field returned by the TikTok scraper
-- (Apify clockworks/tiktok-scraper, profile export). Column names are
-- quoted/lowercase because several source fields use "/" (e.g. authorMeta/avatar),
-- which Snowflake only allows inside double-quoted identifiers.
CREATE TABLE IF NOT EXISTS "TIKTOK_DASHBOARD"."PUBLIC"."tiktok_raw" (
    "authorMeta/avatar" VARCHAR,
    "authorMeta/bioLink" VARCHAR,
    "authorMeta/commerceUserInfo/commerceUser" BOOLEAN,
    "authorMeta/createTime" NUMBER(38, 0),
    "authorMeta/digg" NUMBER(38, 0),
    "authorMeta/fans" NUMBER(38, 0),
    "authorMeta/followDatasetUrl" VARCHAR,
    "authorMeta/following" NUMBER(38, 0),
    "authorMeta/friends" NUMBER(38, 0),
    "authorMeta/hasActiveStory" BOOLEAN,
    "authorMeta/heart" NUMBER(38, 0),
    "authorMeta/id" NUMBER(38, 0),
    "authorMeta/name" VARCHAR,
    "authorMeta/nickName" VARCHAR,
    "authorMeta/originalAvatarUrl" VARCHAR,
    "authorMeta/privateAccount" BOOLEAN,
    "authorMeta/profileUrl" VARCHAR,
    "authorMeta/roomId" VARCHAR,
    "authorMeta/signature" VARCHAR,
    "authorMeta/ttSeller" BOOLEAN,
    "authorMeta/verified" BOOLEAN,
    "authorMeta/video" NUMBER(38, 0),
    collectCount NUMBER(38, 0),
    commentCount NUMBER(38, 0),
    commentsDatasetUrl VARCHAR,
    createTime NUMBER(38, 0),
    createTimeISO TIMESTAMP_NTZ,
    "detailedMentions/0/id" NUMBER(38, 0),
    "detailedMentions/0/name" VARCHAR,
    "detailedMentions/0/nickName" VARCHAR,
    "detailedMentions/0/profileUrl" VARCHAR,
    diggCount NUMBER(38, 0),
    fromProfileSection VARCHAR,
    hasTikTokShopProduct BOOLEAN,
    "hashtags/0/name" VARCHAR,
    "hashtags/1/name" VARCHAR,
    "hashtags/2/name" VARCHAR,
    "hashtags/3/name" VARCHAR,
    "hashtags/4/name" VARCHAR,
    "hashtags/5/name" VARCHAR,
    "hashtags/6/name" VARCHAR,
    "hashtags/7/name" VARCHAR,
    "hashtags/8/name" VARCHAR,
    "hashtags/9/name" VARCHAR,
    "hashtags/10/name" VARCHAR,
    "hashtags/11/name" VARCHAR,
    "hashtags/12/name" VARCHAR,
    "hashtags/13/name" VARCHAR,
    "hashtags/14/name" VARCHAR,
    "hashtags/15/name" VARCHAR,
    "hashtags/16/name" VARCHAR,
    id NUMBER(38, 0),
    input VARCHAR,
    isAd BOOLEAN,
    isMuted BOOLEAN,
    isPinned BOOLEAN,
    isSlideshow BOOLEAN,
    isSponsored BOOLEAN,
    isStory BOOLEAN,
    "locationMeta/address" VARCHAR,
    "locationMeta/city" VARCHAR,
    "locationMeta/cityCode" NUMBER(38, 0),
    "locationMeta/countryCode" NUMBER(38, 0),
    "locationMeta/locationId" NUMBER(38, 0),
    "locationMeta/locationName" VARCHAR,
    "mentions/0" VARCHAR,
    "musicMeta/coverMediumUrl" VARCHAR,
    "musicMeta/musicAlbum" VARCHAR,
    "musicMeta/musicAuthor" VARCHAR,
    "musicMeta/musicId" NUMBER(38, 0),
    "musicMeta/musicName" VARCHAR,
    "musicMeta/musicOriginal" BOOLEAN,
    "musicMeta/originalCoverMediumUrl" VARCHAR,
    "musicMeta/playUrl" VARCHAR,
    playCount NUMBER(38, 0),
    repostCount NUMBER(38, 0),
    shareCount NUMBER(38, 0),
    shortDramaSeriesInfo VARCHAR,
    "slideshowImageLinks/0/downloadLink" VARCHAR,
    "slideshowImageLinks/0/tiktokLink" VARCHAR,
    "slideshowImageLinks/1/downloadLink" VARCHAR,
    "slideshowImageLinks/1/tiktokLink" VARCHAR,
    "slideshowImageLinks/2/downloadLink" VARCHAR,
    "slideshowImageLinks/2/tiktokLink" VARCHAR,
    "slideshowImageLinks/3/downloadLink" VARCHAR,
    "slideshowImageLinks/3/tiktokLink" VARCHAR,
    "slideshowImageLinks/4/downloadLink" VARCHAR,
    "slideshowImageLinks/4/tiktokLink" VARCHAR,
    text VARCHAR,
    textLanguage VARCHAR,
    "videoMeta/aiVideoDescription" VARCHAR,
    "videoMeta/aiVideoSummary" VARCHAR,
    "videoMeta/coverUrl" VARCHAR,
    "videoMeta/definition" VARCHAR,
    "videoMeta/duration" NUMBER(38, 0),
    "videoMeta/format" VARCHAR,
    "videoMeta/height" NUMBER(38, 0),
    "videoMeta/originalCoverUrl" VARCHAR,
    "videoMeta/subtitleLinks" VARCHAR,
    "videoMeta/subtitleLinks/0/downloadLink" VARCHAR,
    "videoMeta/subtitleLinks/0/language" VARCHAR,
    "videoMeta/subtitleLinks/0/source" VARCHAR,
    "videoMeta/subtitleLinks/0/sourceUnabbreviated" VARCHAR,
    "videoMeta/subtitleLinks/0/tiktokLink" VARCHAR,
    "videoMeta/subtitleLinks/0/version" VARCHAR,
    "videoMeta/subtitleLinks/1/downloadLink" VARCHAR,
    "videoMeta/subtitleLinks/1/language" VARCHAR,
    "videoMeta/subtitleLinks/1/source" VARCHAR,
    "videoMeta/subtitleLinks/1/sourceUnabbreviated" VARCHAR,
    "videoMeta/subtitleLinks/1/tiktokLink" VARCHAR,
    "videoMeta/subtitleLinks/1/version" VARCHAR,
    "videoMeta/transcriptionLink" VARCHAR,
    "videoMeta/width" NUMBER(38, 0),
    webVideoUrl VARCHAR
);

-- Clean, analysis-ready table the dashboard actually queries.
-- Only the fields the Shiny app needs, with sane names/types.
CREATE OR REPLACE TABLE "TIKTOK_DASHBOARD"."PUBLIC"."tiktok_videos" (
    video_id       VARCHAR,
    video_url      VARCHAR,
    caption        VARCHAR,
    post_date      TIMESTAMP_NTZ,
    views          NUMBER,
    likes          NUMBER,
    comments       NUMBER,
    shares         NUMBER,
    saves          NUMBER,
    duration_secs  NUMBER,
    cover_url      VARCHAR,
    is_sponsored   BOOLEAN,
    is_ad          BOOLEAN,
    is_pinned      BOOLEAN
);
